djangoBook/mysite/blog/urls.py
from django.urls import path,re_path 
from blog import views

app_name = 'blog'
urlpatterns = [
    
    # Exapmle
    path('',views.PostLV.as_view(),name='index'),

    #EXample : /blog/post/ (same as /blog/)
    path('post/',views.PostLV.as_view(),name='post_list'),
    #Example : /blog/post/django-example/
    re_path(r'^post/?P<slug>[-\w]+)/$',views.PostDV.as_view(),name='post_detail'),

    # Example /blog/archice/
    path('archive/',views.PostAV.as_view(),name='post_archive'),
    # Example /blog/archive/2019 
    path('archive/<int:year>/',views.PostYAV.as_view(),name='post_year_archive'),
    # Example /blog/archive/2019/nov
    path('archive/<int:year>/<str:month>/',views.PostMAV.as_view(),name='post_month'),
    # Example /blog/archive/2019/nov/10
    path('archive/<int:year>/<str:month>/<int:day>/'.views.PostDAV.as_view(),name='post_day_archive'),
    # Example /blog/archive/today
    path('archive/today/',views.PostTAV.as_view(),name='post_today_archive'),

]

djangoBook/mysite/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV,BookmarkDV 


app_name = 'bookmark'

urlpatterns = [
    
    path('',BookmarkLV.as_view(),name='index'),
    path('<int:pk>/',BookmarkDV.as_view(),name='detail'),
]

djangoBook/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

# from bookmark.views import BookmarkLV,BookmarkDV
urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls'))
    # # class-based views
    # path('bookmark/',BookmarkLV.as_view(),name='index'),
    # path('bookmark/<int:pk>/',BookmarkDV.as_view(),name="detail"),
]

djangoBook/mysite/blog/models.py
from django.db import models
from django.urls import reverse 

# Create your models here.


class Post(models.Model):
    title = models.CharField(verbose_name="TITLE",max_length=50)
    slug = models.SlugField("SLUG",unique=True,allow_unicode=True,help_text="one word for title alias.")
    description = models.CharField(("DESCRIPTION"), max_length=100,blank=True,help_text="simple description text")
    content = models.TextField("CONTENT")
    created_dt = models.DateField(("CREATE DATE"), auto_now_add=True)
    modify_dt = models.DateField(("MODIFY DATE"), auto_now=True)

    class Meta :
        verbose_name = "post"
        verbose_name_plural = "posts"
        db_table = "blog_posts"
        ordering = ('-modify_dt',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=(self.slug,))
    def get_previous(self):
        return self.get_previous_by_modify_dt() 
    def get_next(self):
        return self.get_next_by_modify_dt()
    

djangoBook/mysite/bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model) :
    title= models.CharField(("Title"), max_length=100,blank=True)
    url = models.URLField(("URL"), max_length=200)

    def __str__(self):
        return self.title
        
    

djangoBook/mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.dates import archiveIndexView,YearArchiveView,MonthArchiveView,DayArchiveView,TodayArchiveView
from blog.models import Post
# Create your views here.
#- ListView

class PostLV(ListView):
    model = Post
    template_name = "blog/post_all.html"
    context_object_name = 'posts'
    paginate_by = 2
# - DetailView
class PostDV(DetailView):
    model = Post
#--- ArchiveView
class PostAV(archiveIndexView):
    model = Post
    date_field = "modify_dt"
    make_object_list = True 
class PostYAV(YearArchiveView):
    model = Post
    date_field = "modify_dt"
    make_object_list= True
class PostMAV(MonthArchiveView):
    model = Post
    date_field = "modify_dt"
    # make_object_list= True
class PostMAV(MonthArchiveView):
    model = Post
    date_field = "modify_dt"
    # make_object_list= True
class PostDAV(DayArchiveView):
    model= Post  
    date_field= "modify_dt"
class PostTAV(TodayArchiveView):
    model =Post 
    date_field= 'modify_dt'

djangoBook/mysite/bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView 
from .models import Bookmark 

class BookmarkLV(ListView):
    model = Bookmark 
    

class BookmarkDV(DetailView):
    model =Bookmark  

djangoBook/mysite/blog/templates/blog/post_all.html
<h1>Blog List</h1>
<br />

{% for post in posts %}
<h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
{{post.modify_at|date:"N d, Y"}}
<p>{{post.description}}</p>
{% endfor %}

<br />
<div>
  <span>
    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previos_page_number}}">PreviousPage</a>
    {% endif %} Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} {%
    {% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">NextPage</a>
    {% end if %}
  </span>
</div>

djangoBook/mysite/blog/templates/blog/post_archive.html
<h1>Post Archives until {% now 'N d, Y'%}</h1>
<ul>
  {% for date in date_list %}
  <li style="display: inline">
    <a href="{% url 'blog:post_year_archive' date|date:'Y'%}">
      Year{{ date|date:"Y" }}</a
    >
  </li>
  {% endfor %}
</ul>
</br>
<div>
<ul>
{% for post in object_list %} 
<li>{{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
<a href="{{post.get_absolute_url}}">
<strong>{{post.title}}</strong></a></li> 
{% endfor %}
</ul>
</div>

djangoBook/mysite/blog/templates/blog/post_archive_day.html
<h1>Post Archvies for {{day:date:"N d, Y"}}</h1>

<div>
  <ul>
    {% for post in object_list %}
    <li>
      {{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
      <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
    </li>
    {% endfor %}
  </ul>
</div>

djangoBook/mysite/blog/templates/blog/post_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y"}}</h1>
<div>
  <ul>
    {% for post in object_list %}
    <li>
      {{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
      <a href="{{post.get_absolute_url}}"><strong>{{post.title}} </strong></a>
    </li>
    {% endfor %}
  </ul>
</div>

djangoBook/mysite/blog/templates/blog/post_archive_year.html
<h1>Post Archives for {{year|date:"Y"}}</h1>
<ul>
  {% for date in date_list %}
  <li style="display: inline">
    <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b'%}">
      {{date|date:"F"}}
    </a>
  </li>
  {% endfor %}
</ul>
<br />
<div>
  <ul>
    {% for post in object_list %}
    <li>
      {{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
      <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
    </li>
    {% endfor %}
  </ul>
</div>

djangoBook/mysite/blog/templates/blog/post_detail.html
<h2>{{object.title}}</h2>
<p>
  {% if object.get_prvious %}
  <a href="{{object.get_previous.get_absolute_url}}" title="View previous post">
    &laquo;-- {{object.get_previous}}
  </a>
  {% endif %} {% if object.get_next %} |
  <a href="{{object.get_next.get_absolute_url}}" title="View next post">
    {{object.get_next}} --&raquo;
  </a>
  {% endif %}
</p>

<p>{{object.modify_dt| date:"j F Y"}}</p>
<br />
<div>{{object.content|linebreaks}}</div>

djangoBook/mysite/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>Django Bookmark Detail</title>
  </head>

  <body>
    <div id="content">
      <h1>{{object.title}}</h1>
      <ul>
        <li>URL : <a href="{{object.url}}"> {{object.url}}</li>
      </ul>
    </div>
  </body>
</html>

djangoBook/mysite/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html>
  <head>
    <title>Django Bookmark List</title>
  </head>

  <body>
    <div id="content">
      <h1>Bookmark List</h1>
      <ul>
        {% for bookmark in object_list %}
        <li><a href="{%url 'detail' bookmark.id %}">{{bookmark}} </a></li>
        {% endfor%}
      </ul>
    </div>
  </body>
</html>